"""Build the corpus help site (samskrtam.ru/corpus-faq/) from docs_site/wiki/.

ZettelkastenWiki Wave-3 pilot #3 (same-hosting angle): a second FTP site on
the samskrtam.ru deploy path, generated by the shared package — see
https://github.com/gasyoun/ZettelkastenWiki. Deploy is done by the
deploy-corpus-faq workflow (FTP secrets gated); locally:

    python docs_site/build_site.py [out_dir]     # default docs_site/_site
"""

from __future__ import annotations

import sys
from pathlib import Path

from zettelkastenwiki import GroupSpec, SiteConfig, Strings, publish

HERE = Path(__file__).resolve().parent

_MONTHS_RU = [
    "января", "февраля", "марта", "апреля", "мая", "июня",
    "июля", "августа", "сентября", "октября", "ноября", "декабря",
]


def format_date_ru(date_str: str, lang: str = "ru") -> str:
    try:
        y, m, d = date_str.split("-")
        return f"{int(d)} {_MONTHS_RU[int(m) - 1]} {y} г."
    except Exception:
        return date_str


CONFIG = SiteConfig(
    base_url="https://samskrtam.ru/corpus-faq",
    site_name="Корпус — справка",
    org_name="Общество ревнителей санскрита",
    org_url="https://samskrtam.ru",
    author="к.ф.н. М.Ю. Гасунс",
    language="ru",
    wiki_root=HERE / "wiki",
    groups=(
        GroupSpec(name="guide", nav_label="Основы", home_style="cards", jsonld_type="article"),
        GroupSpec(name="faq", nav_label="Вопросы", home_style="accordion", jsonld_type="faq"),
    ),
    strings=Strings(
        search_placeholder="Поиск по справке…",
        search_aria="Поиск по справке",
        nav_toggle_aria="Меню",
        shortcuts_aria="Быстрые ссылки",
        updated_label="Обновлено",
        related_heading="Связанные страницы",
        cta_heading="Следующий шаг",
        read_more="Читать →",
        details_label="Подробнее →",
        sitemap_label="sitemap",
    ),
    format_date=format_date_ru,
    seo_title_suffix=" — справка корпуса",
    default_cta_primary=("Открыть корпус", "https://samskrtam.ru/parallel-corpus/"),
    default_cta_secondary=("Задать вопрос в Telegram", "https://t.me/rusamskrtam"),
    home_title="Справка параллельного санскритско-русского корпуса",
    home_description=(
        "Как пользоваться корпусом Самудра-мантхана: поиск (обычный, regex, "
        "морфологический), читалка, цитирование, состав текстов, права и мобильный доступ."
    ),
    footer_extra_html='<a href="https://samskrtam.ru/parallel-corpus/">корпус</a>',
    emit_htaccess=True,
)


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "_site"
    publish(CONFIG, out)
    print(f"Corpus help site built at {out}")
