#!/usr/bin/env python3
"""documentation_index_check.py — keep DOCUMENTATION_INDEX.md covering every doc (H5426, E016 wave 6).

_Created: 24-09-2026 · Last updated: 24-09-2026_

The index was hand-maintained and fell behind: on 24-09-2026 it named 23 of the
88 Markdown files under the repo root and `docs/`, so 65 docs were invisible to
any human or agent orienting from it. This script makes the coverage half
generated: the hand-written sections above the generated marker stay hand-owned
(they carry the editorial verdict current/supporting/historical), and everything
not mentioned there is listed in one generated section below it.

Usage:
    python scripts/documentation_index_check.py --check   # exit 1 when a doc is unlisted
    python scripts/documentation_index_check.py --fix     # rewrite the generated section

Exit 0 = every scanned doc appears in the index
Exit 1 = --check found unlisted docs (run --fix)
Exit 2 = usage / IO error
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "DOCUMENTATION_INDEX.md"

BEGIN = "<!-- BEGIN GENERATED: uncategorised-docs (scripts/documentation_index_check.py) -->"
END = "<!-- END GENERATED: uncategorised-docs -->"

# Every Markdown file the index is responsible for: repo root + docs/ (recursive).
# web/, papers/, docs_site/ and Corpus_builder/ carry their own local READMEs and
# are named individually by the hand-written sections when they matter.
SCAN_GLOBS = ("*.md", "docs/**/*.md")

MD_REF_RE = re.compile(r"[`(\[]([A-Za-z0-9_./-]+\.md)[`)\]]")


def scanned_docs() -> list[str]:
    seen: set[str] = set()
    for pattern in SCAN_GLOBS:
        for path in ROOT.glob(pattern):
            if not path.is_file():
                continue
            seen.add(path.relative_to(ROOT).as_posix())
    return sorted(seen)


def referenced(text: str) -> set[str]:
    # only a leading "./" is stripped — a leading dot is part of the name (.ai_state.md)
    out = set()
    for m in MD_REF_RE.finditer(text):
        ref = m.group(1)
        out.add(ref[2:] if ref.startswith("./") else ref)
    return out


def hand_written_half(text: str) -> str:
    """The index text excluding the generated section — what the human owns."""
    if BEGIN in text:
        return text.split(BEGIN, 1)[0]
    return text


def missing(text: str) -> list[str]:
    refs = referenced(hand_written_half(text))
    out = []
    for doc in scanned_docs():
        if doc in refs or Path(doc).name in refs:
            continue
        out.append(doc)
    return out


def first_heading(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except OSError:
        pass
    return ""


def render(docs: list[str]) -> str:
    lines = [
        BEGIN,
        "",
        "## Every other Markdown file (generated)",
        "",
        "Generated by [`scripts/documentation_index_check.py`](https://github.com/gasyoun/SamudraManthanam/blob/main/scripts/documentation_index_check.py)",
        "— every `*.md` under the repo root and `docs/` that the hand-written sections above do",
        "not name. Presence here is coverage, **not** a current/supporting/historical verdict:",
        "promote a file into a section above the moment its status matters.",
        "",
        f"{len(docs)} file(s):",
        "",
    ]
    for doc in docs:
        title = first_heading(ROOT / doc)
        suffix = f": {title}" if title else ""
        lines.append(f"- [`{doc}`](https://github.com/gasyoun/SamudraManthanam/blob/main/{doc}){suffix}")
    lines += ["", END]
    return "\n".join(lines)


def apply_fix(text: str, docs: list[str]) -> str:
    block = render(docs)
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    # First run: insert before the closing signature line if there is one.
    marker = "\n_Dr. Mārcis Gasūns_"
    if marker in text:
        head, tail = text.rsplit(marker, 1)
        return head.rstrip("\n") + "\n\n" + block + "\n" + marker + tail
    return text.rstrip("\n") + "\n\n" + block + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report unlisted docs, exit 1 when any")
    ap.add_argument("--fix", action="store_true", help="rewrite the generated section in place")
    args = ap.parse_args(argv)
    if not (args.check or args.fix):
        ap.error("pass --check or --fix")
    if not INDEX.exists():
        print(f"ERROR: {INDEX} not found", file=sys.stderr)
        return 2

    text = INDEX.read_text(encoding="utf-8")
    gaps = missing(text)
    total = len(scanned_docs())
    print(f"scanned {total} doc(s) (root + docs/) · {total - len(gaps)} listed by hand · {len(gaps)} uncategorised")

    if args.fix:
        new = apply_fix(text, gaps)
        if new != text:
            INDEX.write_text(new, encoding="utf-8")
            print(f"wrote generated section: {len(gaps)} file(s) -> DOCUMENTATION_INDEX.md")
        else:
            print("generated section already current")
        return 0

    # --check judges the GENERATED section, not the hand-written half: a doc the
    # human never categorised is fine as long as the generated block lists it.
    if apply_fix(text, gaps) != text:
        for doc in gaps:
            if doc not in text:
                print(f"  UNLISTED {doc}")
        print("FAIL: generated section is stale — run "
              "`python scripts/documentation_index_check.py --fix`")
        return 1
    print(f"PASS: every scanned doc appears in the index ({len(gaps)} via the generated section)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
